# Generated by Django 5.1.15 on 2026-06-16 17:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air_quality", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="airqualityobservation",
            new_name="air_quality_aqi_960338_idx",
            old_name="aq_aqi_obs_idx",
        ),
        migrations.RenameIndex(
            model_name="airqualityobservation",
            new_name="air_quality_state_i_975cfb_idx",
            old_name="aq_state_obs_idx",
        ),
        migrations.RenameIndex(
            model_name="airqualityobservation",
            new_name="air_quality_county__1308b6_idx",
            old_name="aq_county_obs_idx",
        ),
        migrations.AddField(
            model_name="airqualityobservation",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="PostGIS point geometry derived from latitude/longitude.",
                null=True,
                srid=4326,
            ),
        ),
        migrations.AlterField(
            model_name="airqualityobservation",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Soft-delete flag. Inactive records are excluded from default querysets.",
            ),
        ),
    ]
