# Generated by Django 5.1.15 on 2026-06-15 17:56

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geodata', '0002_alter_county_area_sq_km_alter_state_area_sq_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft-delete flag. Inactive records are excluded from default querysets.')),
                ('alert_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=50)),
                ('urgency', models.CharField(max_length=50)),
                ('certainty', models.CharField(max_length=50)),
                ('headline', models.TextField()),
                ('description', models.TextField()),
                ('instruction', models.TextField(blank=True, null=True)),
                ('effective', models.DateTimeField()),
                ('expires', models.DateTimeField()),
                ('affected_zones', models.JSONField(default=list)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StormEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft-delete flag. Inactive records are excluded from default querysets.')),
                ('event_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('begin_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('begin_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('end_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('magnitude', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('magnitude_type', models.CharField(blank=True, max_length=20, null=True)),
                ('deaths_direct', models.IntegerField(default=0)),
                ('injuries_direct', models.IntegerField(default=0)),
                ('damage_property_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('damage_crops_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('episode_narrative', models.TextField(blank=True, null=True)),
                ('event_narrative', models.TextField(blank=True, null=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storm_events', to='geodata.county')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storm_events', to='geodata.state')),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'begin_date'], name='storms_stor_event_t_0ed131_idx'), models.Index(fields=['county', 'event_type'], name='storms_stor_county__f25d7f_idx')],
            },
        ),
    ]
