# Generated by Django 5.1.15 on 2026-06-15 16:56

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geodata", "0002_alter_county_area_sq_km_alter_state_area_sq_km"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeforestationAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when this record was last updated."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Soft-delete flag. Inactive records are excluded from default querysets.",
                    ),
                ),
                ("alert_date", models.DateField(db_index=True)),
                ("confidence", models.CharField(max_length=20)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("alert_type", models.CharField(max_length=50)),
                (
                    "area_ha",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                ("raw_payload", models.JSONField(blank=True, null=True)),
                (
                    "county",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deforestation_alerts",
                        to="geodata.county",
                    ),
                ),
            ],
            options={
                "ordering": ["-alert_date"],
            },
        ),
        migrations.CreateModel(
            name="TreeCoverBaseline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when this record was last updated."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Soft-delete flag. Inactive records are excluded from default querysets.",
                    ),
                ),
                ("year", models.IntegerField(db_index=True)),
                ("tree_cover_percent", models.DecimalField(decimal_places=2, max_digits=5)),
                ("tree_cover_area_ha", models.DecimalField(decimal_places=2, max_digits=12)),
                ("data_source", models.CharField(max_length=50)),
                ("raw_payload", models.JSONField(blank=True, null=True)),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tree_cover_baselines",
                        to="geodata.county",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "county__name"],
                "unique_together": {("county", "year", "data_source")},
            },
        ),
        migrations.CreateModel(
            name="TreeCoverLoss",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when this record was last updated."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Soft-delete flag. Inactive records are excluded from default querysets.",
                    ),
                ),
                ("year", models.IntegerField(db_index=True)),
                ("loss_area_ha", models.DecimalField(decimal_places=2, max_digits=12)),
                ("loss_percent", models.DecimalField(decimal_places=2, max_digits=5)),
                ("primary_driver", models.CharField(blank=True, max_length=100, null=True)),
                ("data_source", models.CharField(max_length=50)),
                ("raw_payload", models.JSONField(blank=True, null=True)),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tree_cover_losses",
                        to="geodata.county",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "county__name"],
                "unique_together": {("county", "year", "data_source")},
            },
        ),
    ]
