# Generated by Django 5.1.15 on 2026-06-15 16:42

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when this record was last updated."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Soft-delete flag. Inactive records are excluded from default querysets.",
                    ),
                ),
                (
                    "fips_code",
                    models.CharField(
                        db_index=True,
                        help_text="2-digit FIPS code (e.g. '06' for California)",
                        max_length=2,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("abbreviation", models.CharField(max_length=2)),
                ("geometry", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                (
                    "area_sq_km",
                    models.DecimalField(
                        decimal_places=2, help_text="Total area in square kilometers", max_digits=12
                    ),
                ),
                ("population", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="County",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when this record was last updated."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Soft-delete flag. Inactive records are excluded from default querysets.",
                    ),
                ),
                (
                    "fips_code",
                    models.CharField(
                        db_index=True,
                        help_text="5-digit FIPS code (State FIPS + County FIPS)",
                        max_length=5,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("geometry", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                (
                    "area_sq_km",
                    models.DecimalField(
                        decimal_places=2, help_text="Total area in square kilometers", max_digits=12
                    ),
                ),
                ("population", models.IntegerField(blank=True, null=True)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counties",
                        to="geodata.state",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "counties",
                "ordering": ["state__name", "name"],
            },
        ),
    ]
