# Generated by Django 5.1.15 on 2026-06-15 18:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geodata", "0002_alter_county_area_sq_km_alter_state_area_sq_km"),
    ]

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when this record was last updated."
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=20)),
                ("risk_type", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=False)),
                ("hyperparameters", models.JSONField(default=dict)),
                ("metrics", models.JSONField(default=dict)),
                ("s3_path", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "unique_together": {("name", "version")},
            },
        ),
        migrations.CreateModel(
            name="CountyRiskScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when this record was last updated."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Soft-delete flag. Inactive records are excluded from default querysets.",
                    ),
                ),
                ("risk_type", models.CharField(max_length=50)),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("confidence", models.DecimalField(decimal_places=2, max_digits=5)),
                ("computed_at", models.DateTimeField()),
                ("factors", models.JSONField(default=dict)),
                ("data_window_start", models.DateField()),
                ("data_window_end", models.DateField()),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_scores",
                        to="geodata.county",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["risk_type", "score"], name="analysis_co_risk_ty_2b50b1_idx"
                    ),
                    models.Index(
                        fields=["county", "risk_type", "-computed_at"],
                        name="analysis_co_county__3c1ea2_idx",
                    ),
                ],
                "unique_together": {("county", "risk_type", "computed_at")},
            },
        ),
        migrations.CreateModel(
            name="FeatureSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when this record was last updated."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Soft-delete flag. Inactive records are excluded from default querysets.",
                    ),
                ),
                ("snapshot_date", models.DateField()),
                ("features", models.JSONField(default=dict)),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="geodata.county"
                    ),
                ),
            ],
            options={
                "unique_together": {("county", "snapshot_date")},
            },
        ),
        migrations.CreateModel(
            name="RiskTrend",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when this record was last updated."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Soft-delete flag. Inactive records are excluded from default querysets.",
                    ),
                ),
                ("risk_type", models.CharField(max_length=50)),
                ("month", models.DateField()),
                ("avg_score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "delta_from_previous",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_trends",
                        to="geodata.county",
                    ),
                ),
            ],
            options={
                "unique_together": {("county", "risk_type", "month")},
            },
        ),
    ]
