# Generated by Django 5.1.15 on 2026-06-15 17:56

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geodata", "0002_alter_county_area_sq_km_alter_state_area_sq_km"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherStation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when this record was last updated."
                    ),
                ),
                ("station_id", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "elevation_m",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "county",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weather_stations",
                        to="geodata.county",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TemperatureObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when this record was last updated."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Soft-delete flag. Inactive records are excluded from default querysets.",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "tmax_celsius",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
                ),
                (
                    "tmin_celsius",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
                ),
                (
                    "tavg_celsius",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
                ),
                (
                    "precipitation_mm",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="weather.weatherstation",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["date", "tmax_celsius"], name="weather_tem_date_62db74_idx"
                    )
                ],
                "unique_together": {("station", "date")},
            },
        ),
    ]
